### ISSUE TITLE
Mobile Orientation Change

### ISSUE THREAD

**Issue by jdemeuse1204** [mac81/pure-drawer#28] opened 2016-03-28 14:18 UTC
Hi Thomas,

Your drawer is amazing, I have gotten a lot of awesome feedback on it.  I am having one problem though, when viewing my website from a mobile device and you change the orientation of your device, the drawer button no longer works.  The icon is there, but when you click on it, nothing happens.  Any help would be greatly appreciated.

Thank you,

James

**Comment by mac81** [comment] 2016-03-28 14:40
Can you tell me what effect your using and on which devices you have this issue? I'm not able to reproduce the issue on any of my devices.

**Comment by jdemeuse1204** [comment] 2016-03-28 15:57
Better yet, here is the link to my test site.  I have a suspicion the issue issue may from the way I am using the drawer.  Essentially I only want the drawer visible for mobile and always visible for desktop, so I did a little rearranging.  It could be from that, however I am not sure.  If that is the case I will close this issue.

Here is the link.

http://skygroundlabs.com/#/Management/MyProfile

**Comment by jdemeuse1204** [comment] 2016-03-28 15:58
I am getting this issue on my iPhone 6 Plus.  It has iOS 9 on it.

**Comment by mac81** [comment] 2016-03-29 14:47
Hmm.. Everything is working fine on my iPhone 6S with your link. Tried opening and closing on both landscape and portrait. Also having it open when changing orientation. 

PS: If you only want the drawer functionality on mobile screens you can just uncomment 

`// $show-drawer: $small-only;`

in the settings file

**Comment by jdemeuse1204** [comment] 2016-03-29 16:01
I updated my iPhone to the latest OS a few days ago, I wonder if it has anything to do with that.  I just went into my browser stack account and tried an iPhone 6S, 6S Plus, and 6 Plus.  They all worked just fine, except those were straight iOS 8.0 and iOS 9.0.  I tried it on my phone again and I still get the same result.  I was tapping around and it looks like when I click under the actual hamburger icon it will work, not when I click on it.  

I tried the site in chrome on my phone and it works just fine.  Seems to be a Safari issue.  

I am not sure what can be done since you are unable to reproduce it on your end.  Do you want me to close out this issue?

PS:  I will try altering the settings so the drawer will only show on mobile screens.  Thanks a million!

**Comment by jdemeuse1204** [comment] 2016-03-30 01:33
Yeah it is very strange.  I am guessing there is some hidden markup like you said.  I am going to try and get my hands on a mac so I can use the developer tools in safari.  If I find out what is wrong I will let you know.  Thank you for all your help!

**Closed** 2017-05-29 06:16 UTC
Labels: Can't reproduce
